### ISSUE TITLE
Request more detailed experimental parameters

### ISSUE THREAD

**Issue by shuaiaihang** [xmed-lab/GenericSSL#10]
Hi,
Thank you very much for your remarkable work. I've conducted experiments on the LA dataset using the configuration consistent with Table 8 in your paper (same with the config file). The obtained results show some variance from those reported in the paper. Could you please advise if there are any additional parameters I should adjust to better replicate your reported results on the LA dataset?

Thank you very much for your assistance.

**Comment by McGregorWwww** [comment]
Hi, thanks for your interest of our work. The variance can be attributed to the variations in the experimental environment and inherent randomness (though we've tried our best to control it). As known, optimal parameters are always differed across different environments. 

To address this, I suggest tuning the parameters based on the training curves recorded with TensorBoard. This will provide valuable insights, particularly if the variance is significant, you can determine whether the model is experiencing overfitting or any other related issues.

Hope this helps.
