### ISSUE TITLE
 SCGM dataset

### ISSUE THREAD

**Issue by wangmingaaaaa** [xmed-lab/GenericSSL#2]
Hello, I would like to ask if you have done experiments on the SCGM dataset?If so, can you share your experimental results on this?

**Comment by McGregorWwww** [comment]
Hello, we haven't conducted those experiments. However, if you're interested, you can give it a try. The provided preprocessing code makes it relatively easy to convert to the SCGM dataset.

**Comment by wangmingaaaaa** [comment]
Thank you for your reply. I tried to run preprocess_mnms.py to process the scgm data set. In preprocess_mnms.py, the line from utils import read_list, read_nifti, config reported an error. I found that there is no read_list, read_nifti in the utils file of the code you disclosed. If you have time, I hope to get your reply.

**Comment by McGregorWwww** [comment]
Actually, the read_list, read_nifti functions are in the `code/utils/__init__.py` file.

The reason why you encountered this issue may be that you did not run `export PYTHONPATH=$(pwd)/code:$PYTHONPATH` to set the 'PYTHONPATH' to 'pwd', as mentioned in the README file.

Hope this helps.

**Comment by wangmingaaaaa** [comment]
Thank you very much for your reply
