### ISSUE TITLE
3d scgm

### ISSUE THREAD

**Issue by wangmingaaaaa** [xmed-lab/GenericSSL#3]
Hello, I would like to ask if you have a way to process the scgm data set that your network can receive? The scgm data sets I processed before were all processed into 2D slices. Can I directly modify your preprocess_mnms.py code? Looking forward to your reply, thank you

**Comment by McGregorWwww** [comment]
Hi, I remember that the original scgm dataset is with 4D data in nii.gz format, the same as mnms dataset, so I think you can directly modify the preprocess_mnms.py code.

**Comment by wangmingaaaaa** [comment]
thank you very much!
