### ISSUE TITLE
The results of training dice on the new data set

### ISSUE THREAD

**Issue by wangmingaaaaa** [xmed-lab/GenericSSL#4]
Hello, sorry to bother you . I have processed the scgm data set and trained it on the genericsl code you provided. This is the result displayed during the training process:
![1](https://github.com/xmed-lab/GenericSSL/assets/139307037/fa8bb479-8a02-42e3-b610-8d24afb2f5cb)
![2](https://github.com/xmed-lab/GenericSSL/assets/139307037/e5297ad2-06e7-414b-bd65-682632daa051)
But the dice value of the running result is very low. Is it because there are too few samples in the scgm data set? This is using 20% of the scgm dataset train_toA_labeled_0.2.txt file, which has only 6 site2-sc03-image site2-sc07-image site3-sc03-image site3-sc08-image site4-sc04-image site4-sc07-image.If you have time, I hope you can give me some suggestions and I look forward to your reply. Thank you so much!

**Comment by McGregorWwww** [comment]
It is more likely the data processing issue, since Synapse dataset has fewer samples. I recommend carefully reviewing the data.
