### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by wangmingaaaaa** [xmed-lab/GenericSSL#6]
Hi, thank you for sharing the code. Does your train_diffusion_2d.py use unet as the backbone?

**Comment by McGregorWwww** [comment]
No, we use a 2D version of V-Net for train_diffusion_2d.py by directly changing the Conv3D to Conv2D.

**Comment by wangmingaaaaa** [comment]
Thank you very much for your reply. I want to compare your code as a baceline. I used unet as the backbone before, so I want to replace your backbone with unet. Do you think it is feasible? Or if I directly use your training results for comparison, is it unfair that the backbone is different?

**Comment by McGregorWwww** [comment]
Sure, it is very easy to change the backbone to unet, I can also give you a rough example in the attachment as reference (may exist bugs).

[DiffUNet.txt](https://github.com/xmed-lab/GenericSSL/files/14338588/DiffUNet.txt)

Furthermore, I've also tried unet before, but there's no big difference, so you may also use the results directly, I think it's fine.

**Comment by wangmingaaaaa** [comment]
Thank you very much, I will try the method you shared to change backbone to unet. I would like to ask, do you still have the results of using unet as the backbone to train on the M&MS data set? If so, can you share it?

**Comment by McGregorWwww** [comment]
Sorry, I did not save the results😅.

**Comment by wangmingaaaaa** [comment]
OK, thank you very much for your patient answer.

**Comment by ieeedre** [comment]
Hello, I conducted an experiment on the m&ms data set according to the DiffUNet.txt you provided. I can achieve an accuracy of about 72% on 2% of the D domain, and an accuracy of about 69% on the 2% of the A domain. , the effect is very different from what you said. I would like to ask if you set some specific parameters when using unet as backbone training?
