### ISSUE TITLE
Running with other dataset

### ISSUE THREAD

**Issue by Yuhanhani** [xmed-lab/GenericSSL#8]
Hi,

Thank you for your great work. Would it be possible to provide a quick guide on how to run this code with different datasets other than the four mentioned in the paper?

Thanks!

**Comment by McGregorWwww** [comment]
Hi, thank you for your interest of our work.

Regarding running with customized datasets, you can follow the pre-processing codes of the four given datasets. The main goal is to convert the nii.gz files to .npy files and generate the corresponding IDs stored in .txt files. 

For example, if your task is semi-supervised segmentation, you can follow `preprocess_synapse.py`. What you should do are: 
1. re-organize your dataset folder like the provided structure of Synapse dataset;
2. change the file paths in utils.config.py;
3. maybe check the ids in https://github.com/xmed-lab/GenericSSL/blob/f1b05bd7639f0e98ebb066f402536099c9fa58f8/code/data/preprocess_synapse.py#L21

If you encounter any further issues, feel free to let me know. Hope this helps.
